version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  api:
    build: ../apps/api
    env_file: ../.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  web:
    build: ../apps/web
    env_file: ../.env
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  pgdata:
  minio:
